### ISSUE TITLE
Nonce error in Managed groups

### ISSUE THREAD

**Issue by tlartaud** [marvinlabs/customer-area#150] opened 2015-08-13 09:46 UTC
( ! ) Notice: Undefined index: wp_cuar_nonce_members in
…/plugins/customer-area-managed-groups/src/php/managed-groups-admin-interface.class.php on line 319

**Comment by ssteinerx** [comment] 2015-08-17 14:48
Do you have a fix for this?  It is holding up deployment of a project that has already been delayed for months due to bugs in the main plugin.

**Comment by vpratfr** [comment] 2015-08-28 07:29
I could not reproduce this issue and I see on the lines where the array index is referenced that we have an `if (isset(...))` check.

@tlartaud Are you using the latest develop branch commit? Can you reproduce that and tell me which line is involved (319 points to a line where no array is read)?

**Comment by vpratfr** [comment] 2015-08-28 08:12
Feel free to reopen if bug is still there.

**Closed by vpratfr** 2015-08-28 08:12 UTC
Labels: bug, Premium add-ons, Priority - high
