### ISSUE TITLE
Function 'save_post_owners' doesn't seem to properly save the owners when called from cuar_create_private_file

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#92] opened 2015-04-17 02:10 UTC
This is the parameters array $files_to_move used to invoke cuar_bulk_create_private_files($files_to_move); 

https://www.dropbox.com/s/p2enyvto85j7lqq/Screenshot%202015-04-16%2022.06.26.png?dl=0

It makes the new post, and stepping through the code, it looks like things are going well, but the files never show up in the private file area, and the files are not moved into the target md5 directory.

I think that looks like the example you gave in the function doc header, but maybe I'm missing something simple?

Thanks,

S

**Comment by vpratfr** [comment] 2015-04-17 12:54
Looks fine. Does the file exist at the specified location?

**Comment by ssteinerx** [comment] 2015-04-17 13:01
Yes, it does and permissions are fine.

Now that I know the parameters are correct, I'll debug further into the Customer Area code.

Thanks,

S

**Comment by ssteinerx** [comment] 2015-04-17 16:44
handle_copy_private_file_from_local_folder is returning null on success, cuar_create_private_file then deletes the file and post.

Change handle_copy_private_file_from_local_folder to return true on success and all is well.

**Comment by ssteinerx** [comment] 2015-04-17 17:21
Found it.  See Github.

S

**Comment by vpratfr** [comment] 2015-04-23 07:30
Ok. Closing this as a duplicate of #94

**Closed by vpratfr** 2015-04-23 07:30 UTC
